      - name: Create Clean Flutter Project in Temp Folder
        run: |
          flutter create temp_app --org com.lapaixducoeur --project-name lapaixducoeur_client --platforms=android
          
          # On remplace le fichier build.gradle entier par une version configurée avec un minSdkVersion à 28
          cat << 'EOF' > temp_app/android/app/build.gradle
          plugins {
              id "com.android.application"
              id "kotlin-android"
              id "dev.flutter.flutter-gradle-plugin"
          }

          android {
              namespace "com.lapaixducoeur.lapaixducoeur_client"
              compileSdkVersion flutter.compileSdkVersion
              ndkVersion flutter.ndkVersion

              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_1_8
                  targetCompatibility JavaVersion.VERSION_1_8
              }

              kotlinOptions {
                  jvmTarget = '1.8'
              }

              defaultConfig {
                  applicationId "com.lapaixducoeur.lapaixducoeur_client"
                  minSdkVersion 28
                  targetSdkVersion flutter.targetSdkVersion
                  versionCode flutterVersionCode.toInteger()
                  versionName flutterVersionName
              }

              buildTypes {
                  release {
                      signingConfig signingConfigs.debug
                  }
              }
          }

          flutter {
              source '../..'
          }
          EOF

          cp -r temp_app/android ./
          cp -r temp_app/ios ./ 2>/dev/null || true
          cp -r temp_app/web ./ 2>/dev/null || true
          rm -rf temp_app
